### ISSUE TITLE
Searching is broken

### ISSUE THREAD

**Issue by regier21** [upcs/cs341-project-ss2020-rust#83]
The following is appearing in the Firefox console: Loading failed for the <script> with source “https://ss2020-rust.herokuapp.com/javascripts/searchbar.js”.

On typing a search in the main page, the following appears in the console:
ReferenceError: search is not definedss2020-rust.herokuapp.com:1:1
    onclick https://ss2020-rust.herokuapp.com/:1

**Comment by vinoya21** [comment]
Searching was taken away from the home screen
