### ISSUE TITLE
Unable to login or register with valid credentials 

### ISSUE THREAD

**Issue by slemly** [upcs/cs341-project-ss2020-rust#94]
Cannot create account on the appspot version of the page with valid credentials; no messages or console logs show any error. Unable to login after account creation on Heroku version of the app.

**Comment by vinoya21** [comment]
Could you clarify this issue? What "valid credentials" did you attempt using?

**Comment by slemly** [comment]
Valid credentials being credentials that were properly formatted without improper characters

**Comment by vinoya21** [comment]
Issue fixed
